### ISSUE TITLE
iPython/Jupyter 4 ShimWarning

### ISSUE THREAD

**Issue by abkfenris** [dpinney/iPythonNotebookServer#2]
When a user is running iPython/Jupyter 4, they will get a `ShimWarning` when iPythonNotebookServer starts a new kernel.

``` python
/usr/local/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
```

**Comment by dpinney** [comment]
I'm thinking this might be an iPython 4.0 issue, although I don't see an issue in their tracker for it.

**Comment by abkfenris** [comment]
I think that's it is just a deprecation warning.

**Comment by dpinney** [comment]
Since I'm forking a shell and a process for iPython I don't have control over the kernel startup, so closing this for now.

Thank you. Good issue.
